import type { InstrumentPreset } from '../engine/types';

export const PRESETS: Record<string, InstrumentPreset> = {
  piano: {
    name: 'Piano',
    oscillatorType: 'triangle',
    oscillatorCount: 2,
    oscillator2Type: 'sine',
    oscillator2Detune: 3,
    oscillator2Gain: 0.6,
    attack: 0.005,
    decay: 0.3,
    sustain: 0.4,
    release: 0.4,
    filterFreq: 4000,
    filterQ: 1,
    filterType: 'lowpass',
    detuneSpread: 5,
    gain: 0.7,
  },
  organ: {
    name: 'Organ',
    oscillatorType: 'sine',
    oscillatorCount: 2,
    oscillator2Type: 'sine',
    oscillator2Detune: 1200, // One octave up (drawbar 8' + 4')
    oscillator2Gain: 0.5,
    attack: 0.01,
    decay: 0.05,
    sustain: 0.9,
    release: 0.08,
    filterFreq: 6000,
    filterQ: 0.5,
    filterType: 'lowpass',
    detuneSpread: 2,
    gain: 0.5,
  },
  pluck: {
    name: 'Pluck',
    oscillatorType: 'sawtooth',
    oscillatorCount: 1,
    attack: 0.001,
    decay: 0.2,
    sustain: 0.05,
    release: 0.15,
    filterFreq: 3000,
    filterQ: 2,
    filterType: 'lowpass',
    detuneSpread: 0,
    gain: 0.6,
  },
  pad: {
    name: 'Soft Pad',
    oscillatorType: 'sine',
    oscillatorCount: 2,
    oscillator2Type: 'triangle',
    oscillator2Detune: 7,
    oscillator2Gain: 0.8,
    attack: 0.3,
    decay: 0.5,
    sustain: 0.7,
    release: 1.0,
    filterFreq: 2000,
    filterQ: 0.7,
    filterType: 'lowpass',
    detuneSpread: 10,
    gain: 0.5,
  },
  bass: {
    name: 'Bass',
    oscillatorType: 'sawtooth',
    oscillatorCount: 1,
    attack: 0.01,
    decay: 0.15,
    sustain: 0.6,
    release: 0.1,
    filterFreq: 800,
    filterQ: 3,
    filterType: 'lowpass',
    detuneSpread: 0,
    gain: 0.8,
  },
};

export const PRESET_KEYS = Object.keys(PRESETS) as readonly (keyof typeof PRESETS)[];
